observer:
  name: GnssroRefNCEP
  obsdatain:
    obsfile: Data/ufo/testinput_tier_1/gnssro_obs_2018041500_s.nc4
  obsdataout:
    obsfile: Data/os/obsout_3dfgat_gnssroref.nc4
  simulated_variables:
    - atmosphericRefractivity
  obs_operator:
    name: GnssroRefNCEP
    obs options:
      use_compress: 0
  obs_error:
    covariance_model: diagonal
  obs_filters:
    - filter: Domain Check
      where:
        - variable:
            name: MetaData/height
          minvalue: 0
          maxvalue: 30000
        - variable:
            name: MetaData/earthRadiusCurvature
          minvalue: 6250000
          maxvalue: 6450000
        - variable:
            name: MetaData/geoidUndulation
          minvalue: -200
          maxvalue: 200
    - filter: Background Check
      apply at iterations: 0,1
      threshold: 3
    - filter: ROobserror
      apply at iterations: 0,1
      variable: refractivity
      errmodel: NCEP
