observer:
  name: Radiosonde
  obsdatain:
    obsfile: Data/ufo/testinput_tier_1/sondes_obs_2018041500_m.nc4
  obsdataout:
    obsfile: Data/os/obsout_3dfgat_sondes.nc4
  simulated_variables:
    - airTemperature
    - windEastward
    - windNorthward
    - specificHumidity
  obs_operator:
    name: VertInterp
    observation alias file: testinput/obsop_name_map.yaml
  obs_error:
    covariance_model: diagonal
  obs_filters:
    - filter: PreQC
      maxvalue: 3
    - filter: Background Check
      apply at iterations: 0,1,2
      threshold: 3
