observer:
  name: SfcCorrected
  obsdatain:
    obsfile: Data/ufo/testinput_tier_1/sfc_obs_2018041500_m.nc4
  obsdataout:
    obsfile: Data/os/obsout_3dfgat_sfc.nc4
  simulated_variables:
    - stationPressure
  obs_operator:
    name: SfcCorrected
    correction scheme to use: UKMO
  linear_obs_operator:
    name: Identity
    observation alias file: testinput/obsop_name_map.yaml
  obs_error:
    covariance_model: diagonal
  obs_filters:
    - filter: PreQC
      maxvalue: 3
    - filter: Difference Check
      apply at iterations: 0,1
      reference: MetaData/stationElevation
      value: GeoVaLs/height_above_mean_sea_level_at_surface
      threshold: 500
    - filter: Background Check
      apply at iterations: 0,1
      threshold: 3
