#!/usr/bin/env python3
"""Analyze MONAN-JEDI provenance traces and produce an execution summary.

The provenance files generated by the temporary Bash workflow are intentionally
simple YAML-like traces. This tool reads the trace directory, extracts the most
important execution metadata, inspects optional tail files, and prints either a
human-readable report or JSON.
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from dataclasses import dataclass
from pathlib import Path
from typing import Any

try:
    import yaml  # type: ignore
except Exception:  # pragma: no cover - handled at runtime
    yaml = None


DEFAULT_TRACE_FILES = {
    "workflow": "workflow.trace",
    "render": "3dvar_fgat.trace",
    "runtime": "runtime.trace",
    "variational": "variational.trace",
    "pbs": "pbs_execution.trace",
    "pbs_render": "3dvar_fgat_pbs.trace",
}

ERROR_PATTERNS = [
    re.compile(r"rank\s+\d+\s+died\s+from\s+signal\s+\d+", re.IGNORECASE),
    re.compile(r"segmentation fault", re.IGNORECASE),
    re.compile(r"signal\s+11", re.IGNORECASE),
    re.compile(r"dumped core", re.IGNORECASE),
    re.compile(r"self%get_data: field not present", re.IGNORECASE),
    re.compile(r"Traceback \(most recent call last\)", re.IGNORECASE),
    re.compile(r"\bERROR\b", re.IGNORECASE),
    re.compile(r"\bFATAL\b", re.IGNORECASE),
    re.compile(r"\bABORT\b", re.IGNORECASE),
]

WARNING_PATTERNS = [
    re.compile(r"\bWARN(?:ING)?\b", re.IGNORECASE),
    re.compile(r"not available", re.IGNORECASE),
    re.compile(r"not found", re.IGNORECASE),
    re.compile(r"missing", re.IGNORECASE),
]


@dataclass
class TraceData:
    name: str
    path: Path
    exists: bool
    parsed: dict[str, Any]
    parse_error: str | None = None


def read_text(path: Path, max_bytes: int | None = None) -> str:
    if not path.exists():
        return ""
    if max_bytes is None:
        return path.read_text(errors="replace")
    data = path.read_bytes()
    if len(data) > max_bytes:
        data = data[-max_bytes:]
    return data.decode(errors="replace")


def parse_trace(path: Path) -> tuple[dict[str, Any], str | None]:
    if not path.exists():
        return {}, None

    text = read_text(path)
    if not text.strip():
        return {}, "empty trace"

    if yaml is None:
        return parse_simple_yaml(text), "PyYAML not available; used simplified parser"

    try:
        parsed = yaml.safe_load(text)
        if isinstance(parsed, dict):
            return parsed, None
        return {}, f"trace did not parse as mapping: {type(parsed).__name__}"
    except Exception as exc:
        return parse_simple_yaml(text), f"YAML parser failed; used simplified parser: {exc}"


def parse_simple_yaml(text: str) -> dict[str, Any]:
    """Very small fallback parser for top-level and one-level key/value traces."""
    root: dict[str, Any] = {}
    current_section: str | None = None

    for raw in text.splitlines():
        if not raw.strip() or raw.lstrip().startswith("#"):
            continue
        indent = len(raw) - len(raw.lstrip(" "))
        line = raw.strip()
        if ":" not in line:
            continue
        key, value = line.split(":", 1)
        key = key.strip()
        value = value.strip()
        value = coerce_scalar(value)

        if indent == 0:
            if value == "":
                root.setdefault(key, {})
                current_section = key
            else:
                root[key] = value
                current_section = None
        elif current_section:
            section = root.setdefault(current_section, {})
            if isinstance(section, dict):
                section[key] = value
    return root


def coerce_scalar(value: str) -> Any:
    if value == "":
        return ""
    if value.lower() == "true":
        return True
    if value.lower() == "false":
        return False
    if value.lower() in {"none", "null"}:
        return None
    try:
        return int(value)
    except ValueError:
        return value


def get_nested(data: dict[str, Any], dotted: str, default: Any = None) -> Any:
    obj: Any = data
    for part in dotted.split("."):
        if not isinstance(obj, dict) or part not in obj:
            return default
        obj = obj[part]
    return obj


def collect_traces(trace_dir: Path) -> dict[str, TraceData]:
    traces: dict[str, TraceData] = {}
    for name, filename in DEFAULT_TRACE_FILES.items():
        path = trace_dir / filename
        parsed, parse_error = parse_trace(path)
        traces[name] = TraceData(name=name, path=path, exists=path.exists(), parsed=parsed, parse_error=parse_error)
    return traces


def scan_patterns(text: str, patterns: list[re.Pattern[str]], limit: int = 12) -> list[str]:
    hits: list[str] = []
    for line in text.splitlines():
        if any(pattern.search(line) for pattern in patterns):
            clean = line.strip()
            if clean and clean not in hits:
                hits.append(clean)
        if len(hits) >= limit:
            break
    return hits


def summarize(traces: dict[str, TraceData], trace_dir: Path) -> dict[str, Any]:
    workflow = traces["workflow"].parsed
    render = traces["render"].parsed
    runtime = traces["runtime"].parsed
    variational = traces["variational"].parsed
    pbs = traces["pbs"].parsed

    pbs_tail = read_text(trace_dir / "pbs_stdout_tail.txt", max_bytes=100_000)
    jedi_tail = read_text(trace_dir / "mpasjedi_variational_tail.txt", max_bytes=100_000)
    qstat_end = read_text(trace_dir / "pbs_qstat_end.txt", max_bytes=100_000)
    nodefile = read_text(trace_dir / "pbs_nodefile.txt", max_bytes=100_000)

    allocated_nodes = sorted({line.strip() for line in nodefile.splitlines() if line.strip() and "not available" not in line})

    trace_presence = {
        name: {
            "path": str(trace.path),
            "exists": trace.exists,
            "parse_error": trace.parse_error,
        }
        for name, trace in traces.items()
    }

    statuses = {
        "workflow": get_nested(workflow, "result.status"),
        "render": get_nested(render, "result.status"),
        "runtime": get_nested(runtime, "result.status"),
        "variational": get_nested(variational, "result.status"),
        "pbs": get_nested(pbs, "result.status"),
    }

    exit_codes = {
        "workflow": get_nested(workflow, "result.exit_code"),
        "render": get_nested(render, "result.exit_code"),
        "runtime": get_nested(runtime, "result.exit_code"),
        "variational": get_nested(variational, "result.exit_code"),
        "pbs": get_nested(pbs, "result.exit_code"),
    }

    errors = {
        "pbs_stdout_tail": scan_patterns(pbs_tail, ERROR_PATTERNS),
        "jedi_log_tail": scan_patterns(jedi_tail, ERROR_PATTERNS),
        "qstat_end": scan_patterns(qstat_end, ERROR_PATTERNS),
    }
    warnings = {
        "pbs_stdout_tail": scan_patterns(pbs_tail, WARNING_PATTERNS),
        "jedi_log_tail": scan_patterns(jedi_tail, WARNING_PATTERNS),
        "qstat_end": scan_patterns(qstat_end, WARNING_PATTERNS),
    }

    failing_stages = [name for name, status in statuses.items() if status not in (None, "completed")]
    missing_traces = [name for name, trace in traces.items() if not trace.exists]

    verdict = "completed"
    if failing_stages:
        verdict = "failed"
    elif any(errors.values()):
        verdict = "completed_with_errors_in_logs"
    elif missing_traces:
        verdict = "incomplete_trace_set"

    return {
        "verdict": verdict,
        "missing_traces": missing_traces,
        "failing_stages": failing_stages,
        "statuses": statuses,
        "exit_codes": exit_codes,
        "timing": {
            "workflow_started_at_utc": workflow.get("started_at_utc"),
            "pbs_started_at_utc": pbs.get("started_at_utc"),
            "pbs_finished_at_utc": get_nested(pbs, "result.finished_at_utc"),
            "pbs_duration_seconds": get_nested(pbs, "result.duration_seconds"),
            "variational_duration_seconds": get_nested(variational, "result.duration_seconds"),
        },
        "pbs": {
            "job_id": get_nested(pbs, "pbs.job_id"),
            "job_name": get_nested(pbs, "pbs.job_name"),
            "queue": get_nested(pbs, "pbs.queue"),
            "select": get_nested(pbs, "pbs.select"),
            "walltime": get_nested(pbs, "pbs.walltime"),
            "place": get_nested(pbs, "pbs.place"),
            "allocated_slot_lines": get_nested(pbs, "node_allocation.allocated_slot_lines", get_nested(pbs, "node_allocation_start.allocated_slot_lines")),
            "allocated_nodes": allocated_nodes,
        },
        "environment": {
            "hostname": get_nested(variational, "runtime_environment.hostname"),
            "mpirun": get_nested(variational, "runtime_environment.mpirun"),
            "mpi_launcher": get_nested(variational, "runtime_environment.mpi_launcher"),
            "mpi_tasks_flag": get_nested(variational, "runtime_environment.mpi_tasks_flag"),
            "mpasjedi_variational_exe": get_nested(variational, "runtime_environment.mpasjedi_variational_exe"),
            "omp_num_threads": get_nested(variational, "runtime_environment.omp_num_threads"),
            "gfortran_convert_unit": get_nested(variational, "runtime_environment.gfortran_convert_unit"),
            "f_ufmtendian": get_nested(variational, "runtime_environment.f_ufmtendian"),
            "fi_cxi_rx_match_mode": get_nested(variational, "runtime_environment.fi_cxi_rx_match_mode"),
            "mpich_smp_single_copy_mode": get_nested(variational, "runtime_environment.mpich_smp_single_copy_mode"),
            "oops_trace": get_nested(variational, "runtime_environment.oops_trace"),
            "oops_debug": get_nested(variational, "runtime_environment.oops_debug"),
        },
        "outputs": {
            "command_file_exists": get_nested(variational, "observed_outputs.command_file.exists"),
            "variational_log_exists": get_nested(variational, "observed_outputs.variational_log.exists", get_nested(pbs, "observed_outputs.jedi_log.exists")),
            "pbs_log_exists": get_nested(pbs, "observed_outputs.pbs_log.exists"),
            "runtime_analysis_entries": get_nested(variational, "observed_outputs.runtime_analysis_dir.entries"),
            "runtime_feedback_entries": get_nested(variational, "observed_outputs.runtime_feedback_dir.entries"),
            "scratch_analysis_entries": get_nested(variational, "observed_outputs.scratch_analysis_dir.entries"),
            "scratch_feedback_entries": get_nested(variational, "observed_outputs.scratch_feedback_dir.entries"),
        },
        "errors": errors,
        "warnings": warnings,
        "trace_presence": trace_presence,
    }


def print_report(summary: dict[str, Any]) -> None:
    print("# MONAN-JEDI provenance summary")
    print()
    print(f"Verdict: {summary['verdict']}")

    if summary["missing_traces"]:
        print(f"Missing traces: {', '.join(summary['missing_traces'])}")
    if summary["failing_stages"]:
        print(f"Failing stages: {', '.join(summary['failing_stages'])}")

    print("\n## Stage status")
    for name, status in summary["statuses"].items():
        exit_code = summary["exit_codes"].get(name)
        print(f"- {name}: {status or 'unknown'}" + (f" (exit={exit_code})" if exit_code is not None else ""))

    print("\n## PBS")
    pbs = summary["pbs"]
    print(f"- job_id: {pbs.get('job_id') or 'unknown'}")
    print(f"- job_name: {pbs.get('job_name') or 'unknown'}")
    print(f"- queue: {pbs.get('queue') or 'unknown'}")
    print(f"- select: {pbs.get('select') or 'unknown'}")
    print(f"- walltime: {pbs.get('walltime') or 'unknown'}")
    print(f"- place: {pbs.get('place') or 'unknown'}")
    print(f"- allocated_slot_lines: {pbs.get('allocated_slot_lines') or 'unknown'}")
    nodes = pbs.get("allocated_nodes") or []
    if nodes:
        print(f"- allocated_nodes: {', '.join(nodes[:12])}" + (" ..." if len(nodes) > 12 else ""))

    print("\n## Runtime environment")
    for key, value in summary["environment"].items():
        print(f"- {key}: {value if value not in (None, '') else 'unknown'}")

    print("\n## Outputs")
    for key, value in summary["outputs"].items():
        print(f"- {key}: {value if value is not None else 'unknown'}")

    print("\n## Detected errors")
    any_error = False
    for source, hits in summary["errors"].items():
        if not hits:
            continue
        any_error = True
        print(f"### {source}")
        for hit in hits:
            print(f"- {hit}")
    if not any_error:
        print("No known error pattern found in captured tails.")

    print("\n## Detected warnings")
    any_warning = False
    for source, hits in summary["warnings"].items():
        if not hits:
            continue
        any_warning = True
        print(f"### {source}")
        for hit in hits[:8]:
            print(f"- {hit}")
    if not any_warning:
        print("No warning pattern found in captured tails.")

    print("\n## Trace files")
    for name, meta in summary["trace_presence"].items():
        suffix = ""
        if meta.get("parse_error"):
            suffix = f" [{meta['parse_error']}]"
        print(f"- {name}: {'present' if meta['exists'] else 'missing'} - {meta['path']}{suffix}")


def write_markdown_report(summary: dict[str, Any], output_path: Path) -> None:
    from io import StringIO

    old_stdout = sys.stdout
    buf = StringIO()
    try:
        sys.stdout = buf
        print_report(summary)
    finally:
        sys.stdout = old_stdout
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(buf.getvalue())


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Analyze MONAN-JEDI provenance traces.")
    parser.add_argument(
        "trace_dir",
        nargs="?",
        default="build/rendered/provenance",
        help="Directory containing *.trace files and captured tails.",
    )
    parser.add_argument("--json", action="store_true", help="Print machine-readable JSON.")
    parser.add_argument(
        "--write-report",
        default=None,
        help="Optional path to write a Markdown report, for example build/rendered/provenance/summary.md.",
    )
    args = parser.parse_args(argv)

    trace_dir = Path(args.trace_dir).resolve()
    traces = collect_traces(trace_dir)
    summary = summarize(traces, trace_dir)

    if args.write_report:
        write_markdown_report(summary, Path(args.write_report))

    if args.json:
        print(json.dumps(summary, indent=2, sort_keys=True))
    else:
        print_report(summary)

    return 0 if summary["verdict"] in {"completed", "completed_with_errors_in_logs"} else 1


if __name__ == "__main__":
    raise SystemExit(main())
